export const FETCH_BUSINESSES = "FETCH_BUSINESSES";
export const FETCHING_BUSINESSES = "FETCHING_BUSINESSES";
export const FETCH_BUSINESSES_SUCCESS = "FETCH_BUSINESSES_SUCCESS";
export const FETCH_BUSINESSES_ERROR = "FETCH_BUSINESSES_ERROR";
export const SET_FILTER_SEARCH = "SET_FILTER_SEARCH";
